[project]
name = "sal-kiti"
version = "1.7.1"
requires-python = ">=3.10"
dependencies = [
    "django==5.2.15",
    "django-cors-headers==4.9.0",
    "django-dry-rest-permissions==1.2.0",
    "django-extensions==4.1",
    "django-filter==25.2",
    "djangorestframework==3.17.1",
    "djangorestframework-queryfields==1.1.0",
    "drf-spectacular==0.29.0",
    "mysqlclient==2.2.8",
    "oauthlib==3.3.1",
    "python-dateutil==2.9.0",
    "python-memcached==1.62",
    "requests==2.34.2",
    "requests-oauthlib==2.0.0",
]

[dependency-groups]
dev = [
    "black==26.5.1",
    "coverage==7.14.1",
    "django==5.2.15",
    "django-cors-headers==4.9.0",
    "django-dry-rest-permissions==1.2.0",
    "django-extensions==4.1",
    "django-filter==25.2",
    "djangorestframework==3.17.1",
    "djangorestframework-queryfields==1.1.0",
    "drf-spectacular==0.29.0",
    "factory-boy==3.3.3",
    "flake8==7.3.0",
    "isort==8.0.1",
    "mysqlclient==2.2.8",
    "oauthlib==3.3.1",
    "python-dateutil==2.9.0",
    "python-memcached==1.62",
    "requests==2.34.2",
    "requests-oauthlib==2.0.0",
    "sphinx==8.1.3",
    "sphinxcontrib-django==2.5",
]


[tool.isort]
profile = "black"
skip_gitignore = true

[tool.black]
line-length = 119
