sonar.projectKey=sal-kiti_sal-kiti
sonar.organization=sal-kiti

sonar.sources=results,sal_kiti,apps
sonar.tests=results/tests/
sonar.test.inclusions=results/tests/**/*.py

sonar.exclusions=.venv/**,**/__pycache__/**,**/migrations/**,docs/**
sonar.python.version=3.10
sonar.python.coverage.reportPaths=coverage.xml