# Generated by Django 2.2.12 on 2020-10-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("divari", "0001_partial_result_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="start_level_longbow",
            field=models.SmallIntegerField(default=1, verbose_name="Longbow start level"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="result",
            name="bow_type",
            field=models.CharField(
                choices=[
                    ("recurve", "Recurve"),
                    ("compound", "Compound"),
                    ("barebow", "Barebow"),
                    ("longbow", "Longbow"),
                ],
                default="recurve",
                max_length=8,
                verbose_name="Bow type",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="bow_type",
            field=models.CharField(
                choices=[
                    ("recurve", "Recurve"),
                    ("compound", "Compound"),
                    ("barebow", "Barebow"),
                    ("longbow", "Longbow"),
                ],
                default="recurve",
                max_length=8,
                verbose_name="Bow type",
            ),
        ),
    ]
