# Generated by Django 2.2.23 on 2021-06-14 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("divari", "0002_auto_20201009_1550"),
    ]

    operations = [
        migrations.AlterField(
            model_name="result",
            name="target_type",
            field=models.CharField(
                choices=[("40", "40 cm"), ("60", "60 cm"), ("80", "80 cm"), ("122", "122 cm")],
                default="40",
                max_length=3,
                verbose_name="Target type",
            ),
        ),
    ]
