# Generated by Django 3.2.16 on 2022-11-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("divari", "0003_auto_20210614_1240"),
    ]

    operations = [
        migrations.AddField(
            model_name="season",
            name="start_level_junbarebow",
            field=models.SmallIntegerField(default=1, verbose_name="Junior Barebow start level"),
        ),
        migrations.AddField(
            model_name="season",
            name="start_level_juncompound",
            field=models.SmallIntegerField(default=1, verbose_name="Junior Compound start level"),
        ),
        migrations.AddField(
            model_name="season",
            name="start_level_junrecurve",
            field=models.SmallIntegerField(default=1, verbose_name="Junior Recurve start level"),
        ),
        migrations.AlterField(
            model_name="result",
            name="bow_type",
            field=models.CharField(
                choices=[
                    ("recurve", "Recurve"),
                    ("compound", "Compound"),
                    ("barebow", "Barebow"),
                    ("longbow", "Longbow"),
                    ("junrecurve", "Junior Recurve"),
                    ("juncompound", "Junior Compound"),
                    ("junbarebow", "Junior Barebow"),
                ],
                default="recurve",
                max_length=11,
                verbose_name="Bow type",
            ),
        ),
        migrations.AlterField(
            model_name="season",
            name="result_count",
            field=models.SmallIntegerField(default=1, verbose_name="Number of included results"),
        ),
        migrations.AlterField(
            model_name="season",
            name="start_level_barebow",
            field=models.SmallIntegerField(default=1, verbose_name="Barebow start level"),
        ),
        migrations.AlterField(
            model_name="season",
            name="start_level_compound",
            field=models.SmallIntegerField(default=1, verbose_name="Compound start level"),
        ),
        migrations.AlterField(
            model_name="season",
            name="start_level_longbow",
            field=models.SmallIntegerField(default=1, verbose_name="Longbow start level"),
        ),
        migrations.AlterField(
            model_name="season",
            name="start_level_recurve",
            field=models.SmallIntegerField(default=1, verbose_name="Recurve start level"),
        ),
        migrations.AlterField(
            model_name="team",
            name="bow_type",
            field=models.CharField(
                choices=[
                    ("recurve", "Recurve"),
                    ("compound", "Compound"),
                    ("barebow", "Barebow"),
                    ("longbow", "Longbow"),
                    ("junrecurve", "Junior Recurve"),
                    ("juncompound", "Junior Compound"),
                    ("junbarebow", "Junior Barebow"),
                ],
                default="recurve",
                max_length=11,
                verbose_name="Bow type",
            ),
        ),
    ]
